// <auto-generated />
namespace BFKH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createdordermenumodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdordermenumodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201606131546546_created order menu model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
